### ISSUE TITLE
Dapper.Contrib [ExplicitKey] attribute behaves like the [Key] attribute when using with IDbConnection.InsertAsync()

### ISSUE THREAD

**Issue by DamienLaw** [StackExchange/Dapper#1076]
I have a model

```
public class TestModel
{
    [ExplicitKey]
    public int ExplicitId1 { get; set; }

    [ExplicitKey]
    public int ExplicitId2 { get; set; }

    public int Property1 { get; set; }
}
```
When I performed a `IDbConnection.InsertAsync()`, everything is working as expected
```
var model = new TestModel
{
    ExplicitId1 = 1,
    ExplicitId2 = 2,
    Property1 = 3
};

await dbConnection.InsertAsync(model);
// The SQL Statement that is being generated:
// INSERT INTO Test (ExplicitId1, ExplicitId2, Property1) VALUES (@ExplicitId1, @ExplicitId2, @Property1)
```

Now, things start to go wrong when I performed an `IDbConnection.UpdateAsync()` first followed by an  `IDbConnection.InsertAsync()`.
```
if (!await dbConnection.UpdateAsync(model))
{
    await dbConnection.InsertAsync(model);
    // The SQL Statement that is being generated:
    // INSERT INTO Test (Property1) VALUES (@Property1)
}
```
The INSERT SQL Statement that is being generated has excluded the Properties decorated with the ExplicitKey attribute. The columns `ExplicitId1` and `ExplicitId2` are composite key in the database table which aren't auto generated but have to be supplied. An error will be thrown if the above INSERT statement is executed since the columns aren't provided.

 I think I have located the source of the problem in the source file [SqlMapperExtensions.Async.cs](https://github.com/StackExchange/Dapper/blob/cd751c21f67348a1327d1073b716f99563d44322/Dapper.Contrib/SqlMapperExtensions.Async.cs#L246)
The line `keyProperties.AddRange(explicitKeyProperties);` adds "Explicit Key Properties" into the list of "Key Properties" effectively considering ExplicitKeys as Keys and caching them for subsequent uses.

**Comment by DamienLaw** [comment]
Oh wait, [this has been fixed](https://github.com/StackExchange/Dapper/commit/307ab7eae89044e7a90c808267e482074d58cfd1) a month ago but only for `UpdateAsync()`.

Shouldn't `DeleteAsync()` be fixed as well since that part is used on both methods?

**Comment by maracuja-juice** [comment]
When will [this change/pre-release](https://www.myget.org/feed/dapper/package/nuget/Dapper.Contrib) be released to NuGet?

**Comment by achaloux** [comment]
`DeleteAsync()` still hasn't been fixed as of 1.60.1

**Comment by psjflynn** [comment]
DeleteAsync() is still an issue with the latest nuget version of Dapper.Contrib. Any ideas @NickCraver or @mgravell? We ran into this issue and it took quite a while to realize what it was so now we reverted to using Dapper instead with ExecuteAsync().

**Comment by achaloux** [comment]
This issue should be closed. It was fixed in pull request #1309 and released in version 2.0.30
